version: '3'
services:
  unifi-video-controller:
    build: .
    container_name: unifi-video-controller
    network_mode: host
    volumes:
      - ./run/data:/var/lib/unifi-video
      - ./run/videos:/var/lib/unifi-video/videos
    tmpfs:
      - /var/cache/unifi-video
    environment:
      - TZ=America/Detroit
      - DEBUG=0
      - CREATE_TMPFS=no
    cap_add:
      - DAC_READ_SEARCH
